### PR TITLE
Make vdr-plugin-mcli dynamically link against "libnetceiver"

### LINKED ISSUE #13: Would it be possible to split out "libmcli" into a separate project?
Haven't tried so far. Maybe it would also be possible to get what I want using "creative fiddling with build parameters". And if you prefer to not split off "libmcli", I'll probably do just that.

My "issue" is that the "libmcli" part can optionally also be used by "minisatip". Currently I'm building "libmcli" directly from a mirror of the Baycom files: https://github.com/VDR4Arch/vdr4arch/blob/master/deps/libmcli/PKGBUILD
And make minisatip depend on it.

Currently it's my "libmcli" package which delivers the "netceiver tools". So building vdr-plugin-mcli including all tools will conflict with my libmcli package.

As "libmcli" is at least used by two projects, I think the proper way of building would be to finally have 3 packages:

libmcli:
- libmcli shared object (.so) file
- pkg-config file so other projects can detect the library
- all the tools to interact and update the netceiver

vdr-plugin-mcli:
- Depends on libmcli
- Contains just the VDR plugin

minisatip:
- Depends on libmcli

What do you think about this?

### PR DESCRIPTION
**Pull request by M-Reimer**
This PR makes vdr-plugin-mcli link dynamically against "libnetceiver".

To make the "log mask" system work, I've created a similar mask in "libnetceiver" and copy over the relevant bits on plugin startup.

### CODE REVIEW

**Comment by pbiering** [comment]
@M-Reimer : good job, well done, will merge next

**Review by pbiering — APPROVED** [review]
tested, working

**Comment by M-Reimer** [comment]
Thanks for merging. I was able to compile and package for Arch, now, but can't get it to work.

Maybe you can have a look at my VDR-Portal thread, here: https://www.vdr-portal.de/forum/index.php?thread/135649-vdr-startet-mit-vdr-plugin-mcli-nicht-error-invalid-primary-device-number-1/

**Comment by pbiering** [comment]
have posted a comment: https://www.vdr-portal.de/forum/index.php?thread/135649-vdr-startet-mit-vdr-plugin-mcli-nicht-error-invalid-primary-device-number-1/&postID=1359171#post1359171

**Pull request merged**
